### ISSUE TITLE
Include trace-summary in offline 2.0 build

### ISSUE THREAD

**Issue by charlesfair** [rocknsm/SimpleRock#76]
Please include the Bro trace-summary utility in the offline build of ROCK 2.0.  Iis not included by default:
https://www.bro.org/sphinx/components/trace-summary/README.html

**Comment by dcode** [comment]
This is built by default in our Bro packages for use with connection logs.
PCAP support is optional and not currently built.

**Comment by charlesfair** [comment]
Great! Conn log analysis is my intent.
