### ISSUE TITLE
Please include the SOF-ELK parsers and dashboards as offline build options 

### ISSUE THREAD

**Issue by charlesfair** [rocknsm/SimpleRock#77]
Please include the SOF-ELK parsers and dashboards, either as a default include with the offline build, or as an option:

"All parsers and dashboards for this VM are now maintained in this Github repository. You can access them directly via http://for572.com/sof-elk-git "

https://github.com/philhagen/sof-elk/blob/master/VM_README.md

**Comment by dcode** [comment]
I'll have to consider this after the 2.0 release.  Not enough time to
integrate this at this point.

**Comment by jeffgeiger** [comment]
The capabilities introduced with SOF-ELK, while terribly useful in the defense of a network, are far afield of the core purpose of what we're trying to achieve.  In a larger scale deployment, with an ELK cluster as opposed to a single instance, you could implement a logstash ingest point with the SOF-ELK configs to complement your NSM data.  With the lift of setting up the ELK cluster already done, it would be a reasonable next step, but not one that falls within the NSM goals of ROCK.
